### ISSUE TITLE
Add example for 2-nic deployment

### ISSUE THREAD

**Issue by codygreen** [f5devcentral/terraform-aws-bigip#13]
Add an example for a 2-nic deployment

**Comment by codygreen** [comment]
for this example you would leverage the mgmt and public subnet_ids to create a 2-nic BIG-IP.  The EC2 network interfaces are assigned via: 

- 0:mgmt
- 1:public
- 2:internal

**Comment by JeffGiroux** [comment]
Added some code and files in PR #36 
https://github.com/f5devcentral/terraform-aws-bigip/pull/36

**Comment by codygreen** [comment]
resolved by @JeffGiroux
