### ISSUE TITLE
F5 A&O Toolchain Install via version not url

### ISSUE THREAD

**Issue by codygreen** [f5devcentral/terraform-aws-bigip#24]
We should switch the A&O toolchain install process to release versions instead of download urls.  This would allow us to support "latest" without the user obtaining the download URL from GitHub.

**Get URL for latest AS3 version**
`curl -s https://api.github.com/repos/F5Networks/f5-appsvcs-extension/releases/latest | jq ".assets[].browser_download_url"`

**Get URL for latest DO version**
`curl -s https://api.github.com/repos/F5Networks/f5-declarative-onboarding/releases/latest | jq ".assets[].browser_download_url"`

**Get URL for latest TS version**
`curl -s https://api.github.com/repos/F5Networks/f5-telemetry-streaming/releases/latest | jq ".assets[].browser_download_url"`

**Get URL for specific AS3 version (3.14.0)**
`curl -s https://api.github.com/repos/F5Networks/f5-appsvcs-extension/releases/tags/v3.14.0 | jq ".assets[].browser_download_url"`

**Comment by mjmenger** [comment]
a latest approach would lead to non-deterministic results. I think that each version of the module should refer to specific versions of DO/AS3/TS.

**Comment by codygreen** [comment]
I agree with mark, while this is a nice feature to have it should be addressed by the F5 Terraform provider.
