### ISSUE TITLE
Escape password variable from AWS Secret Manager

### ISSUE THREAD

**Issue by codygreen** [f5devcentral/terraform-aws-bigip#30]
@chen23 pointed out that https://github.com/codygreen/terraform-aws-bigip/blob/master/f5_onboard.tmpl#L229 could allow remote execution.

This is not in the master branch but in the fork for the 0.1.2 milestone.

**Comment by mjmenger** [comment]
doesn't it still presuppose the availability of the private key?

**Comment by codygreen** [comment]
I need to research this, but if the user put a remote execution string in the AWS Secret Manager the user data script could possibly execute it when setting the password. You would be doing this to yourself but it's still a concern we should address.

**Comment by codygreen** [comment]
after further evaluation, I believe we should be able to trust the value coming from the AWS secrets manager so trying to escape its value would not be necessary.
