### ISSUE TITLE
AS3 Install Failure

### ISSUE THREAD

**Issue by codygreen** [f5devcentral/terraform-aws-bigip#34]
Do not try to install AS3 if the download failed.

I'm seeing SSL validation errors against GitHub when attempting to download AS3 3.15:

`curl: (35) Unknown SSL protocol error in connection to github-production-release-asset-2e65be.s3.amazonaws.com:443`

However, DO download does not produce this error

**Comment by codygreen** [comment]
Initial thoughts on this:
- update the f5_onboard script to validate that the rpm file was downloaded successfully and validates against the SHA 256 hash before attempting to install

**Comment by mjmenger** [comment]
are you able to reliably recreate this? If so, can you provide an example that causes the failure?

**Comment by codygreen** [comment]
I have not been able to reproduce this error over the last week of development.
